// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARyFA9QWzfsgbftV3J_K6WmwXzmU3crCI',
    appId: '1:126099945418:web:3256270e67a40a9a38c133',
    messagingSenderId: '126099945418',
    projectId: 'flutter-test-app-60404',
    authDomain: 'flutter-test-app-60404.firebaseapp.com',
    storageBucket: 'flutter-test-app-60404.appspot.com',
    measurementId: 'G-8WVF0HHZ0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbfTqVyQBE0Y9ipWdz5mZCVE9obfdt1E4',
    appId: '1:126099945418:android:5dd17b26fdb7cc6a38c133',
    messagingSenderId: '126099945418',
    projectId: 'flutter-test-app-60404',
    storageBucket: 'flutter-test-app-60404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjETc84tpmijfMYbKFkqbx8AqEEDXsWRE',
    appId: '1:126099945418:ios:430143586f0f5e9f38c133',
    messagingSenderId: '126099945418',
    projectId: 'flutter-test-app-60404',
    storageBucket: 'flutter-test-app-60404.appspot.com',
    iosClientId: '126099945418-cm33nu9r9r1ug5mcsh5gc8smfdrfspak.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjETc84tpmijfMYbKFkqbx8AqEEDXsWRE',
    appId: '1:126099945418:ios:9e01f9c8367b797438c133',
    messagingSenderId: '126099945418',
    projectId: 'flutter-test-app-60404',
    storageBucket: 'flutter-test-app-60404.appspot.com',
    iosClientId: '126099945418-ig4t3j3sv5pg3igivh4379fvmbin8e5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSetup.RunnerTests',
  );
}
